### ISSUE TITLE
Email invalid...

### ISSUE THREAD

**Issue by greatfireball** [imixs/imixs-office-workflow#319]
I am using the docker compose file to evaluate the Office-Workflow package. Unfortunately, my email address is rejected as invalid, but I used my current and working email address. Where is the email address validation and can that behavior easily be changed?

Thx in advance!

**Comment by rsoika** [comment]
This sounds interesting. The email address is simply validated against a regular expression

    ^[_A-Za-z0-9-\\+]+(\\.[_A-Za-z0-9-]+)*@[A-Za-z0-9-]+(\\.[A-Za-z0-9]+)*(\\.[A-Za-z]{2,})$

It is more likely that there was an error in the setup phase and there is now already a profile with this address. What exactly is the error message s.serer?

**Comment by greatfireball** [comment]
Thanks for your answer. It seems that there is a little mistake inside the used pattern. Inside the second domain group `(\\.[A-Za-z0-9]+)*` no hyphens are allowed. Thus, my email address fails your validation process. Nevertheless, given the definition of allowed local part in email addresses (see [RFC 5322](https://tools.ietf.org/html/rfc5322)) maybe other valid email addresses will fail also.

Therefore, my suggesting for a new pattern recognizing my email address would be:

```
^[_A-Za-z0-9-\\+]+(\\.[_A-Za-z0-9-]+)*@[A-Za-z0-9-]+(\\.[-A-Za-z0-9]+)*(\\.[A-Za-z]{2,})$
```

If you can provide me a hint, where that pattern is located, I can also prepare a pull request.

**Comment by rsoika** [comment]
Thanks a lot for your investigation!
The regex is located in one of the Marty-Plugins here:
https://github.com/imixs/imixs-marty/blob/master/imixs-marty-ejb/src/main/java/org/imixs/marty/plugins/ProfilePlugin.java

I will change this in the master branch (upcoming version 4.1.0) 
Can you please post an example for the address pattern that is currently not working for you. I will add than a junit test also.

**Comment by rsoika** [comment]
Issue is fixed in upcoming version 5.1.

Thanks again for your finding!

**Comment by greatfireball** [comment]
Thanks for the fix... I can provide an example email address, of course. Currently, I am working at a German university. German university tend to have the suffix `uni-` prefix for their second level domains. Therefore, in my current email address the second level is `uni-giessen` or an older employer was the `uni-wuerzburg`. In case of a second level domain, everything works find, but as soon, as a third or fourth level domain is used, the pattern will fail. For example my current email address follows the following format:

`firstname.lastname@department.faculty.uni-giessen.de`

Hope that helps and sorry for the delay...

**Comment by rsoika** [comment]
ok, I checked several combinations. Your regex works fine. 
We will release the new Version 4.1.0 soon.....

**Comment by greatfireball** [comment]
thx, I am looking forward to the release!

**Comment by rsoika** [comment]
Version 4.1.0 is now available on Docker-Hub - maybe you can give it a try.
